name: Deploy

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install deps
      run: npm install
    - name: Publish
      uses: wrangler@2.19.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
